// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.example.servicea.person;

public interface PersonRequestIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:person.PersonRequestId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
