// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.example.servicea.person;

public interface PersonReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:person.PersonReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string surname = 3;</code>
   * @return The surname.
   */
  java.lang.String getSurname();
  /**
   * <code>string surname = 3;</code>
   * @return The bytes for surname.
   */
  com.google.protobuf.ByteString
      getSurnameBytes();

  /**
   * <code>string carId = 4;</code>
   * @return The carId.
   */
  java.lang.String getCarId();
  /**
   * <code>string carId = 4;</code>
   * @return The bytes for carId.
   */
  com.google.protobuf.ByteString
      getCarIdBytes();
}
