// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.example.servicea.person;

public interface PersonRequestCarIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:person.PersonRequestCarId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string carId = 1;</code>
   * @return The carId.
   */
  java.lang.String getCarId();
  /**
   * <code>string carId = 1;</code>
   * @return The bytes for carId.
   */
  com.google.protobuf.ByteString
      getCarIdBytes();
}
